### ISSUE TITLE
Request for Code 

### ISSUE THREAD

**Issue by salvatoreferragamo** [BinWang28/InstructDS_train#1]
Thanks for your work! It has inspired me a lot.
So could you release this part of code to let me quickly follow up your work.
Thanks!

**Comment by BinWang28** [comment]
Thanks for your interest. I am diligently working on it. Hopefull to have it next week.

**Comment by salvatoreferragamo** [comment]
Thanks for your reply!
I am looking forward to your good news. Thanks again.

**Comment by BinWang28** [comment]
Updated!
